[2020-11-23 13:00:28,037] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 13:03:15,876] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 14:14:57,041] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 14:31:37,112] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 14:34:48,756] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 14:38:10,213] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 14:38:41,651] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 14:40:28,363] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 14:57:08,337] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 15:18:02,894] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 15:58:47,025] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-23 16:00:40,571] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-24 16:16:16,784] SEVERE {b7a.log.crash} - java.lang.NullPointerException 
org.ballerinalang.jvm.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:125)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.invokeTestFunction(BTestRunner.java:601)
	at org.ballerinalang.test.runtime.BTestRunner.executeFunction(BTestRunner.java:436)
	at org.ballerinalang.test.runtime.BTestRunner.lambda$executeTests$2(BTestRunner.java:332)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.test.runtime.BTestRunner.executeTests(BTestRunner.java:320)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:291)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:106)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: java.lang.NullPointerException
	at roland.asb.0_1_0.tests.main_test.testReceiveFromQueueOperation(tests/main_test.bal:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-11-27 10:46:51,105] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 10:55:03,887] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 10:57:17,868] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 10:59:06,457] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 11:00:31,753] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 11:05:31,009] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 11:32:59,572] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 11:36:25,938] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 11:46:02,003] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 13:38:49,501] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 15:12:34,275] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 15:21:10,557] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 15:33:38,429] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 15:43:41,025] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 15:57:10,849] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 15:58:39,666] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 16:00:28,725] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 16:33:14,804] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 16:36:42,887] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 16:39:32,492] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 16:43:21,374] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 17:02:57,200] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-27 17:43:41,745] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 08:59:18,697] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 09:06:07,706] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 10:17:14,038] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 10:17:51,331] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 10:19:34,542] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 10:30:20,857] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 10:37:32,333] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 12:42:23,143] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 12:50:50,880] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 12:53:28,151] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 16:25:32,459] SEVERE {b7a.log.crash} - Test [testReceiveFromSubscriptionOperation] depends on function [testSendToTopicOperation], but it couldn't be found. 
org.ballerinalang.jvm.util.exceptions.BallerinaException: Test [testReceiveFromSubscriptionOperation] depends on function [testSendToTopicOperation], but it couldn't be found.
	at org.ballerinalang.test.runtime.BTestRunner.checkCyclicDependencies(BTestRunner.java:176)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:102)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-11-30 17:24:29,509] SEVERE {b7a.log.crash} - Test [testCompleteOneMessageFromSubscriptionOperation] depends on function [testSendToQueueOperation], but it couldn't be found. 
org.ballerinalang.jvm.util.exceptions.BallerinaException: Test [testCompleteOneMessageFromSubscriptionOperation] depends on function [testSendToQueueOperation], but it couldn't be found.
	at org.ballerinalang.test.runtime.BTestRunner.checkCyclicDependencies(BTestRunner.java:176)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:102)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:18:58,862] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:19:51,667] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:21:46,266] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:23:13,694] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:27:02,078] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:27:41,818] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:30:29,318] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:31:37,206] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 11:34:01,602] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 12:39:54,812] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 12:44:52,450] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 15:12:43,354] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 15:54:58,522] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:08:40,785] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:12:48,928] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:18:15,286] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:21:18,011] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:23:46,417] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:24:39,627] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:25:37,068] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:36:39,160] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:38:11,161] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:38:59,408] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:46:03,176] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:46:54,767] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:48:18,702] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 16:59:13,669] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 17:19:11,146] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 17:32:15,677] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 17:35:34,524] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 20:03:15,327] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 20:08:45,385] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
